### ISSUE TITLE
Chp 7, Section 2 Lexical Decision model fails during sampling

### ISSUE THREAD

**Issue by drussellmrichie** [abrsvn/pyactr-book#1] opened 2021-04-19 23:03 UTC
Hi, I'm trying to fit the lexical decision model in Chapter 7, section 2, and I get an error during inference:

```
<ipython-input-23-0006ec3856d7>:33: FutureWarning: In v4.0, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  trace = pm.sample(draws=10000, n_init=200000, cores=6, progressbar=True)
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (6 chains in 6 jobs)
NUTS: [threshold, noise, latency_factor, intercept, decay]
<IPython.core.display.HTML object>

C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\step_methods\hmc\quadpotential.py:224: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\step_methods\hmc\quadpotential.py:203: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\step_methods\hmc\quadpotential.py:224: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\step_methods\hmc\quadpotential.py:203: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\step_methods\hmc\quadpotential.py:224: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(1, self._stds, out=self._inv_stds)
C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\step_methods\hmc\quadpotential.py:203: RuntimeWarning: invalid value encountered in multiply
  return np.multiply(self._var, x, out=out)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\parallel_sampling.py", line 137, in run
    self._start_loop()
  File "C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\parallel_sampling.py", line 191, in _start_loop
    point, stats = self._compute_point()
  File "C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\parallel_sampling.py", line 216, in _compute_point
    point, stats = self._step_method.step(self._point)
  File "C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\step_methods\arraystep.py", line 276, in step
    apoint, stats = self.astep(array)
  File "C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\step_methods\hmc\base_hmc.py", line 147, in astep
    self.potential.raise_ok(self._logp_dlogp_func._ordering.vmap)
  File "C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\step_methods\hmc\quadpotential.py", line 272, in raise_ok
    raise ValueError("\n".join(errmsg))
ValueError: Mass matrix contains zeros on the diagonal. 
The derivative of RV `noise_interval__`.ravel()[0] is zero.
The derivative of RV `intercept_interval__`.ravel()[0] is zero.
"""


The above exception was the direct cause of the following exception:

ValueError: Mass matrix contains zeros on the diagonal. 
The derivative of RV `noise_interval__`.ravel()[0] is zero.
The derivative of RV `intercept_interval__`.ravel()[0] is zero.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-23-0006ec3856d7>", line 33, in <module>
    trace = pm.sample(draws=10000, n_init=200000, cores=6, progressbar=True)

  File "C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\sampling.py", line 559, in sample
    trace = _mp_sample(**sample_args, **parallel_args)

  File "C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\sampling.py", line 1477, in _mp_sample
    for draw in sampler:

  File "C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\parallel_sampling.py", line 479, in __iter__
    draw = ProcessAdapter.recv_draw(self._active)

  File "C:\Users\druss\Anaconda3\envs\mypm3env\lib\site-packages\pymc3\parallel_sampling.py", line 359, in recv_draw
    raise error from old_error

RuntimeError: Chain 1 failed.
```

The only thing I've changed in the code is changing `n_jobs` to `cores`, since I'm using a different version of pymc3. Otherwise, I have left your script as is. Also, the first model (the log frequency model) fit just fine.

Have you seen this before? Any idea what the issue is?

**Comment by abrsvn** [comment] 2021-04-19 23:08
Try to run it with the following package versions:

pip3 install --upgrade 'arviz==0.11.1'
pip3 install --upgrade 'pymc3==3.9.3'

and let us know what happens. thank you for going through the book so
carefully,

-a

**Comment by drussellmrichie** [comment] 2021-04-19 23:22
Thanks for your quick response. I'm enjoying the book so far. I just made a fresh Python 3.8 conda environment, pip installed arviz and pymc3 to those versions, and now the model won't even compile:

```
with lex_dec_model:
    # prior for base activation
    decay = pm.Uniform('decay', lower=0, upper=1)
    # priors for latency
    intercept = pm.Uniform('intercept', lower=0, upper=2)
    latency_factor = pm.Uniform('latency_factor', lower=0, upper=5)
    # priors for accuracy
    noise = pm.Uniform('noise', lower=0, upper=5)
    threshold = pm.Normal('threshold', mu=0, sd=10)
    # compute activation
    scaled_time = time ** (-decay)
    def compute_activation(scaled_time_vector):
        compare = tt.isinf(scaled_time_vector)
        subvector = scaled_time_vector[(1-compare).nonzero()]
        activation_from_time = tt.log(subvector.sum())
        return activation_from_time
    activation_from_time, _ = theano.scan(fn=compute_activation,\
                                          sequences=scaled_time)
    
    # latency likelihood
    mu_rt = pm.Deterministic('mu_rt', intercept +\
                          latency_factor*tt.exp(-activation_from_time))
    rt_observed = pm.Normal('rt_observed', mu=mu_rt, sd=0.01,\
                            observed=rt)
    
    # accuracy likelihood
    odds_reciprocal = tt.exp(-(activation_from_time - threshold)/noise)
    mu_prob = pm.Deterministic('mu_prob', 1/(1 + odds_reciprocal))
    prob_observed = pm.Normal('prob_observed', mu=mu_prob, sd=0.01,\
                              observed=accuracy)

You can find the C code in this temporary file: C:\Users\druss\AppData\Local\Temp\theano_compilation_error_29efru6r
Traceback (most recent call last):

  File "<ipython-input-8-3c217a318305>", line 3, in <module>
    decay = pm.Uniform('decay', lower=0, upper=1)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\distributions\distribution.py", line 82, in __new__
    dist = cls.dist(*args, **kwargs)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\distributions\distribution.py", line 91, in dist
    dist.__init__(*args, **kwargs)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\distributions\continuous.py", line 193, in __init__
    self.mean = (upper + lower) / 2.

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\theano\tensor\var.py", line 131, in __add__
    return theano.tensor.basic.add(self, other)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\theano\gof\op.py", line 669, in __call__
    thunk = node.op.make_thunk(node, storage_map, compute_map,

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\theano\gof\op.py", line 954, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map,

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\theano\gof\op.py", line 857, in make_c_thunk
    outputs = cl.make_thunk(input_storage=node_input_storage,

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\theano\gof\cc.py", line 1215, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\theano\gof\cc.py", line 1153, in __compile__
    thunk, module = self.cthunk_factory(error_storage,

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\theano\gof\cc.py", line 1623, in cthunk_factory
    module = get_module_cache().module_from_key(

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\theano\gof\cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\theano\gof\cc.py", line 1520, in compile_cmodule
    module = c_compiler.compile_str(

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\theano\gof\cmodule.py", line 2410, in compile_str
    raise Exception('Compilation failed (return status=%s): %s' %

Exception: ("Compilation failed (return status=1): C:\\Users\\druss\\AppData\\Local\\Temp\\ccYLRO9j.o: In function `run':\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:99: undefined reference to `__imp__Py_NoneStruct'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:124: undefined reference to `__imp_PyExc_ValueError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:130: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:158: undefined reference to `__imp_PyExc_NotImplementedError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:195: undefined reference to `__imp__Py_NoneStruct'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:210: undefined reference to `__imp_PyExc_ValueError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:479: undefined reference to `__imp_PyExc_NotImplementedError'\r. C:\\Users\\druss\\AppData\\Local\\Temp\\ccYLRO9j.o: In function `_Py_INCREF':\r. C:/Users/druss/Anaconda3/envs/pyactr_book/include/object.h:459: undefined reference to `__imp__Py_NoneStruct'\r. C:\\Users\\druss\\AppData\\Local\\Temp\\ccYLRO9j.o: In function `run':\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:485: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:244: undefined reference to `__imp_PyExc_NotImplementedError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:265: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:173: undefined reference to `__imp_PyExc_TypeError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:179: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:515: undefined reference to `__imp__Py_NoneStruct'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:514: undefined reference to `__imp__Py_NoneStruct'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:516: undefined reference to `__imp__Py_NoneStruct'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:259: undefined reference to `__imp_PyExc_TypeError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:279: undefined reference to `__imp__Py_NoneStruct'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:294: undefined reference to `__imp_PyExc_ValueError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:328: undefined reference to `__imp_PyExc_NotImplementedError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:349: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:216: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:343: undefined reference to `__imp_PyExc_TypeError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:300: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:397: undefined reference to `__imp_PyExc_RuntimeError'\r. C:\\Users\\druss\\AppData\\Local\\Temp\\ccYLRO9j.o: In function `instantiate':\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:550: undefined reference to `__imp_PyExc_TypeError'\r. C:\\Users\\druss\\AppData\\Local\\Temp\\ccYLRO9j.o: In function `_import_array':\r. C:/Users/druss/Anaconda3/envs/pyactr_book/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1480: undefined reference to `__imp_PyCapsule_Type'\r. C:/Users/druss/Anaconda3/envs/pyactr_book/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1481: undefined reference to `__imp_PyExc_RuntimeError'\r. C:\\Users\\druss\\AppData\\Local\\Temp\\ccYLRO9j.o: In function `PyInit_m03cc3cdee46c6787a94521175277126c8d483d4e6ac5026e943ac127eec8e49a':\r. C:/Users/druss/AppData/Local/Theano/compiledir_Windows-10-10.0.19041-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.8-64/tmp4w0zjqwn/mod.cpp:583: undefined reference to `__imp_PyExc_ImportError'\r. C:\\Users\\druss\\AppData\\Local\\Temp\\ccYLRO9j.o: In function `_import_array':\r. C:/Users/druss/Anaconda3/envs/pyactr_book/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1512: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/Anaconda3/envs/pyactr_book/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1496: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/Anaconda3/envs/pyactr_book/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1502: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/Anaconda3/envs/pyactr_book/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1524: undefined reference to `__imp_PyExc_RuntimeError'\r. C:/Users/druss/Anaconda3/envs/pyactr_book/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1476: undefined reference to `__imp_PyExc_AttributeError'\r. C:/Users/druss/Anaconda3/envs/pyactr_book/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1488: undefined reference to `__imp_PyExc_RuntimeError'\r. collect2.exe: error: ld returned 1 exit status\r. ", '[Elemwise{add,no_inplace}(TensorConstant{1.0}, TensorConstant{0.0})]')
```

The log_freq_model doesn't compile now either. I will now try Python 3.6 since that is what the PyMC3 devs say they test on.

**Comment by drussellmrichie** [comment] 2021-04-19 23:44
I tried making a new conda environment in 3.6, , and installing the arviz/pymc3 versions you suggested, and now I get yet a different error with the first model:

```
import numpy as np
import pandas as pd
import pymc3 as pm
# from pymc3.backends import Text
# from pymc3.backends.text import load

freq = np.array([242, 92.8, 57.7, 40.5, 30.6, 23.4, 19,\
                 16, 13.4, 11.5, 10, 9, 7, 5, 3, 1])
rt = np.array([542, 555, 566, 562, 570, 569, 577, 587,\
               592, 605, 603, 575, 620, 607, 622, 674])/1000
accuracy = np.array([97.22, 95.56, 95.56, 96.3, 96.11, 94.26,\
                     95, 92.41, 91.67, 93.52, 91.85, 93.52,\
                     91.48, 90.93, 84.44, 74.63])/100

log_freq_model = pm.Model()
with log_freq_model:
    # priors
    intercept = pm.Normal('intercept', mu=0, sd=300)
    slope = pm.Normal('slope', mu=0, sd=300)
    sigma = pm.HalfNormal('sigma', sd=300)
    # likelihood
    mu = pm.Deterministic('mu', intercept + slope*np.log(freq))
    observed_rt = pm.Normal('observed_rt', mu=mu, sd=sigma,\
                            observed=rt)

with log_freq_model:
    # db = Text('./data/log_freq_model_trace')
    trace = pm.sample(draws=5000, tune=15000,
                      cores=4)
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, slope, intercept]
Traceback (most recent call last):

  File "<ipython-input-2-c3751f21ec1d>", line 29, in <module>
    cores=4)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\sampling.py", line 545, in sample
    trace = _mp_sample(**sample_args, **parallel_args)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\sampling.py", line 1481, in _mp_sample
    pickle_backend=pickle_backend,

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 454, in __init__
    for chain, seed, start in zip(range(chains), seeds, start_points)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 454, in <listcomp>
    for chain, seed, start in zip(range(chains), seeds, start_points)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 294, in __init__
    self._process.start()

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

BrokenPipeError: [Errno 32] Broken pipe


Process worker_chain_1:
Traceback (most recent call last):
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 137, in run
    self._start_loop()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 178, in _start_loop
    msg = self._recv_msg()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 169, in _recv_msg
    return self._msg_pipe.recv()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 232, in _run_process
    _Process(*args).run()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 144, in run
    self._msg_pipe.send(("error", None, e))
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
Process worker_chain_0:
Traceback (most recent call last):
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 137, in run
    self._start_loop()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 178, in _start_loop
    msg = self._recv_msg()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 169, in _recv_msg
    return self._msg_pipe.recv()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 232, in _run_process
    _Process(*args).run()
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\parallel_sampling.py", line 144, in run
    self._msg_pipe.send(("error", None, e))
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] The pipe is being closed
```

**Comment by abrsvn** [comment] 2021-04-19 23:45
thank you for all this. on my linux machine, this code works:

log_freq_model = pm.Model()
with log_freq_model:
    # priors
    intercept = pm.Normal('intercept', mu=0, sd=300)
    slope = pm.Normal('slope', mu=0, sd=300)
    sigma = pm.HalfNormal('sigma', sd=300)
    # likelihood
    mu = pm.Deterministic('mu', intercept + slope*np.log(freq))
    observed_rt = pm.Normal('observed_rt', mu=mu, sd=sigma,\
                            observed=rt)

with log_freq_model:
    db = Text('./log_freq_model_trace')
    trace = pm.sample(draws=5000, trace=db, tune=15000,\
                      n_init=200000, cores=4)

the same for this code:

time = theano.shared(time_freq(freq), 'time')


lex_dec_model = pm.Model()
with lex_dec_model:
    # prior for base activation
    decay = pm.Uniform('decay', lower=0, upper=1)
    # priors for latency
    intercept = pm.Uniform('intercept', lower=0, upper=2)
    latency_factor = pm.Uniform('latency_factor', lower=0, upper=5)
    # priors for accuracy
    noise = pm.Uniform('noise', lower=0, upper=5)
    threshold = pm.Normal('threshold', mu=0, sd=10)
    # compute activation
    scaled_time = time ** (-decay)
    def compute_activation(scaled_time_vector):
        compare = tt.isinf(scaled_time_vector)
        subvector = scaled_time_vector[(1-compare).nonzero()]
        activation_from_time = tt.log(subvector.sum())
        return activation_from_time
    activation_from_time, _ = theano.scan(fn=compute_activation,\
                                          sequences=scaled_time)
    # latency likelihood
    mu_rt = pm.Deterministic('mu_rt', intercept +\
                          latency_factor*tt.exp(-activation_from_time))
    rt_observed = pm.Normal('rt_observed', mu=mu_rt, sd=0.01,\
                            observed=rt)
    # accuracy likelihood
    odds_reciprocal = tt.exp(-(activation_from_time - threshold)/noise)
    mu_prob = pm.Deterministic('mu_prob', 1/(1 + odds_reciprocal))
    prob_observed = pm.Normal('prob_observed', mu=mu_prob, sd=0.01,\
                              observed=accuracy)

with lex_dec_model:
    db = Text('./lex_dec_model_trace')
    trace = pm.sample(draws=10000, trace=db,\
                      n_init=200000, cores=6)

I'm running all this on a Debian-based machine, Python 3.8.5, pymc3 3.9.3, theano 1.0.5

I wonder if being on a Windows machine is part of the issue. I'll need a couple of weeks, or maybe more, to try to reproduce all this on my Windows system.

You could try to run all this on google colab (which spins up Debian-based machines) and see if everything works OK there. You can find some examples of google colab notebooks in the "notebooks" folder in this repo. Pls let us know how it goes with Python 3.6, colab etc. All this is very useful information. Thank you!

**Comment by abrsvn** [comment] 2021-04-19 23:47
Re the Python 3.6 error: can you pls try to run the model with only 1 core? just trying to rule out that multiprocessing is not the issue here.

**Comment by drussellmrichie** [comment] 2021-04-19 23:55
Ah, you're right -- it appears to do with multiprocessing:

https://github.com/pymc-devs/pymc3/issues/3388

I set `cores=1`, and now the first model works again. Currently running `lex_dec_model`

**Comment by abrsvn** [comment] 2021-04-20 00:04
that's great. thank you for all this work. i'm going to close this issue since it seems to be related to pymc3/theano and multiprocessing on Win10, but please let us know if you find a solution for it, i'll keep this in mind also.

**Comment by drussellmrichie** [comment] 2021-04-20 00:21
Unfortunately the model failed again, even when using a single core.

```python
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Sequential sampling (2 chains in 1 job)
NUTS: [threshold, noise, latency_factor, intercept, decay]
Traceback (most recent call last):

  File "<ipython-input-2-75b49bf92436>", line 52, in <module>
    trace = pm.sample(draws=10000, cores=1, progressbar=True)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\sampling.py", line 586, in sample
    trace = _sample_many(**sample_args)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\sampling.py", line 707, in _sample_many
    **kwargs,

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\sampling.py", line 846, in _sample
    for it, (strace, diverging) in enumerate(sampling):

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\fastprogress\fastprogress.py", line 47, in __iter__
    raise e

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\fastprogress\fastprogress.py", line 41, in __iter__
    for i,o in enumerate(self.gen):

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\sampling.py", line 1003, in _iter_sample
    point, stats = step.step(point)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\step_methods\arraystep.py", line 263, in step
    apoint, stats = self.astep(array)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\step_methods\hmc\base_hmc.py", line 154, in astep
    self.potential.raise_ok(self._logp_dlogp_func._ordering.vmap)

  File "C:\Users\druss\Anaconda3\envs\pyactr_book\lib\site-packages\pymc3\step_methods\hmc\quadpotential.py", line 263, in raise_ok
    raise ValueError('\n'.join(errmsg))

ValueError: Mass matrix contains zeros on the diagonal. 
The derivative of RV `threshold`.ravel()[0] is zero.
The derivative of RV `noise_interval__`.ravel()[0] is zero.
The derivative of RV `intercept_interval__`.ravel()[0] is zero.
```

Here's all the version info:

    PyMC3 Version: 3.9.3
    Theano Version: 1.0.5
    Python Version: 3.6.13
    Operating system: Win10
    How did you install PyMC3: Pip

**Comment by abrsvn** [comment] 2021-06-01 16:25
apologies for the late reply, the last several weeks have been very hectic. switching the sampler to SMC fixes this issue, as shown here:

https://colab.research.google.com/github/abrsvn/pyactr-book/blob/master/notebooks/35_lex_dec_ACTR_model_1.ipynb

it might take a long time to get 20k draws though, so reducing the number to 5k or 2k should help. if you have access to a cluster (even a small one), this should be no problem, but it should be OK even on a good desktop machine.

thank you for your patience, please let us know if this works on your end.

**Comment by abrsvn** [comment] 2021-06-17 19:15
Closing this since the issue is resolved by using the SMC sampler.

**Closed as completed by abrsvn** 2021-06-17 19:15 UTC
